### ISSUE TITLE
没有hard positive和hard negative会不会很慢？

### ISSUE THREAD

**Issue by lliuz** [luhaofang/tripletloss#29]
看代码里没有实现hard positive和hard negative

**Comment by wangpichao** [comment]
for i in range(self.triplet):
            positive_feature = bottom[0].data[i+self.triplet]
            a_p = archor_feature - positive_feature
            ap = np.dot(a_p,a_p)
            aps[i+self.triplet] = ap

What's the meaning of these codes?
