### ISSUE TITLE
Question about Anchors

### ISSUE THREAD

**Issue by ZoroDerVonCodier** [luhaofang/tripletloss#40]
This may be a silly question, but in order to get convergence, do you always need to use the same anchors for the entire training session, or can the anchors be selected at random from within the DataLayer forward pass?

Thanks!

**Comment by luhaofang** [comment]
@ZoroDerVonCodier Hi, It's random sampling,  an epoch training means every sample is picked as anchor for one time.

**Comment by ZoroDerVonCodier** [comment]
Perfect! Thanks.
